# Run The scraper
name: Run scraper

on:
  schedule:
  - cron:  '3 4 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    # cf. https://docs.github.com/en/github/setting-up-and-managing-billing-and-payments-on-github/about-billing-for-github-actions
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
    
    - name: Increase git buffer size
      run: |
        git config --global http.postBuffer 1048576000
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run Python script
      run: |
        python scraper.py
      
    - name: Push log files to repo
      uses: github-actions-x/commit@v2.9
      with:
        push-branch: 'main'
        commit-message: 'Scraper done'
        force-add: 'true'
        files: tools/
        name: autoupdate

    - name: Push contents of data folder to repo
      uses: github-actions-x/commit@v2.9
      with:
        push-branch: 'main'
        commit-message: 'Scraper done'
        force-add: 'true'
        files: data/ 
        name: autoupdate
        
