name: Mail services alert

on:
  push:
    paths:
      - 'data/geoservices_changestats_CH.csv'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  checkChangeStatsFile:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.ChangeStatsFileIsChanged.outputs.FileHasChanged }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Get changed CSV files in the data folder
        id: changed-files-specific
        uses: tj-actions/changed-files@v35
        with:
          files: data/*changestats*.csv
          
      - name: Set environment variable regarding file change to default (FALSE)
        run: echo "FileHasChanged=FALSE" >> $GITHUB_ENV
      
      - name: Set environment variable regarding file change
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          echo "One or more files in the docs folder has changed."
          echo "List all the files that have changed: ${{ steps.changed-files-specific.outputs.all_changed_files }}"
          echo "FileHasChanged=TRUE" >> $GITHUB_ENV

      - name: Print diagnosis regarding file change
        run: |
          echo "Has the file changed?" 
          echo ${{ env.FileHasChanged }}
          
      - uses: dawidd6/action-send-mail@v3
        if: ${{ env.FileHasChanged }} == "TRUE"
        with:
          server_address: ${{secrets.MAIL_SMTP_SERVER}}
          server_port: 465
          secure: true
          username: ${{secrets.MAIL_USER_NAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Significant changes in geoservices availability
          to: mail@ralphstraumann.ch
          from: Geoservice Harvester
          body: Geoservice Harvester has found significant changes in geoservices availability in its last run. This might mean that some data owners have changed endpoints of their geoservices. Check the [statistics](https://github.com/rastrau/geoservice_harvester_poc/blob/main/data/geoservices_changestats_CH.csv) or the attached file.
          ignore_cert: true
          convert_markdown: true
          attachments: ./data/geoservices_changestats_CH.csv
          priority: normal
